apiVersion: v1
kind: Service
metadata:
  labels:
    name: domd-app
  name: domd-app
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: domd-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
